# docker-compose.yml
version: '3'

services:
  weaviate:
    image: semitechnologies/weaviate:1.19.6
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - legal-analyzer-network

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - legal-analyzer-network
    volumes:
      - ./data:/app/data

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    networks:
      - legal-analyzer-network

networks:
  legal-analyzer-network:

volumes:
  weaviate_data: